name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Solana
        working-directory: ./school
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli
          sudo apt-get update
          sudo apt-get install -y libudev-dev
          cargo install --git https://github.com/solana-labs/rbpf build-bpf --tag v0.2.39
          anchor build
          anchor test
